---
services:

  guacd:
    container_name: guacd
    image: guacamole/guacd:1.6.0
    networks:
      - guacamole

    environment:
      LOG_LEVEL: debug
    volumes:
      - /etc/localtime:/etc/localtime:ro

  guacamole:
    container_name: guacamole
    build: ./guacamole
    environment:
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOME: /etc/guacamole
      # CONSOLE_TITLE: test title
      ENABLE_WEBSOCKET: "true"
      # START_COMMAND: "docker run --rm --network  docker_guacamole --name $$hostname -e 'VNC_PW=test' consol/centos-xfce-vnc || true"
      START_COMMAND: extensions/start.sh
      # STOP_COMMAND: "docker stop -t 120  $$hostname && echo stopping && sleep  60"
      STOP_COMMAND: "extensions/stop.sh $$hostname"
      SHUTDOWN_DELAY: 90
      COMMAND_TIMEOUT: 6000
      IDLE_TIME: 20
      DISCONNECT_TIME: 1200
    volumes:
      - ./extensions/:/etc/guacamole/extensions/:z
      - ./user-mapping.xml:/etc/guacamole/user-mapping.xml:z
      - ./logback.xml:/etc/guacamole/logback.xml:z
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - guacamole
    depends_on:
      - guacd
    ports:
      - "9000:8080"

networks:
  guacamole:
