version: "3"
services:

  guacd:
    container_name: guacd
    image: guacamole/guacd:1.2.0
    networks:
      - guacamole

    environment:
      GUACD_LOG_LEVEL: debug
    volumes:
      - /etc/localtime:/etc/localtime:ro

  guacamole:
    container_name: guacamole
    build: ./guacamole
    environment:
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOME: /etc/guacamole
      ENABLE_WEBSOCKET: "true"
      START_COMMAND: "timeout -s 9 15 docker run --rm --network  docker_guacamole --name $$hostname -e 'VNC_PW=test' consol/centos-xfce-vnc || true"
      STOP_COMMAND: "docker stop -t 120  $$hostname"
      SHUTDOWN_DELAY: 30
      COMMAND_TIMEOUT: 30
      IDLE_TIME: 30
      DISCONNECT_TIME: 60
      # API_SESSION_TIMEOUT: 1

    volumes:
      - ./extensions/:/etc/guacamole/extensions/:z
      - ./user-mapping.xml:/etc/guacamole/user-mapping.xml:z
      - ./logback.xml:/etc/guacamole/logback.xml:z
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - guacamole
    depends_on:
      - guacd
    ports:
      - "80:8080"

networks:
  guacamole:
